### PR TITLE
default images on small screen removed

### PR DESCRIPTION
**Pull request by ayusharma**
ref #5 @daviddao Please take a look.

### CODE REVIEW

**Comment by daviddao** [comment]
I am not sure if we should remove the images instead of replacing them. I think @jessica-jordan would know better.

**Comment by jayjayjpg** [comment]
@ayusharma Thanks for the PR! I agree with @daviddao that we should rather replace the placeholder images here. Could you include them once I have attached a couple of those to this issue @ayusharma ? I should be able to come up with a couple of suitable ones by tomorrow

**Comment by ayusharma** [comment]
@jessica-jordan Yes. I'll do that :)

**Comment by jayjayjpg** [comment]
[dev-slider.zip](https://github.com/biojs/biojs.net2/files/210197/dev-slider.zip)

@ayusharma With a slight delay, here are finally the images for the slider section on the mobile view of the developers' page. I already added the last image in my recent [commit](https://github.com/biojs/biojs.net2/commit/a07f58233e00cf28b6371d802b924596b63b5c71), but can you also fix the other ones with the respective titles?
1. Headline: Multiple Sequence Alignment
   Subheadline: Visualize sequence alignments with the (MSA BioJS component |link in new tab to: http://biojs.io/d/msa)
2. Headline: Genome browsing
   Subheadline: Lightweight and easy with the (CTTV Genome BioJS component | link in new tab to: http://biojs.io/d/cttv.genome)
3. Headline: Analysis of Genomic Data
   Subheadline: Find interesting variants in your genomic data using the (Dnaism BioJS component | link in new tab to: http://biojs.io/d/dnaism)
4. Headline: Find over 130 other components in the (BioJS registry | link in new tab: http://biojs.io)
   Subheadline: (Browse the registry| link in new tab: http://biojs.io)

Many thanks!

**Comment by jayjayjpg** [comment]
Looking great, LGTM!

**Pull request merged**
